<?php
// Load the server name global setting from the DB.
function get_servername_setting()
{
        global $CFG;
        if (isset($CFG->block_panopto_servername)){
            return $CFG->block_panopto_servername;
        }
        throw new moodle_exception('not defined');
        return false;
}

// Load the instance name global setting from the DB.
function get_instancename_setting()
{
        global $CFG;
        if (isset($CFG->block_panopto_instancename)){
            return $CFG->block_panopto_instancename;
        }
        throw new moodle_exception('not defined');
        return false;
}

// Load the application key global setting from the DB.
function get_application_key_setting()
{
	global $CFG;
        if (isset($CFG->block_panopto_applicationkey)){
            return $CFG->block_panopto_applicationkey;
        }
        throw new moodle_exception('not defined');
        return false;
}

// Prepend the instance name to the Moodle course ID to create an external ID for Panopto CourseCast.
function decorate_course_id($moodle_course_id)
{
	return (get_instancename_setting() . ":" . $moodle_course_id);
}

// Decorate a moodle username with the instancename outside the context of a panopto_data object.
function decorate_username($moodle_username)
{
	return (get_instancename_setting() . "\\" . $moodle_username); 
}

// Sign the payload with the proof that it was generated by trusted code. 
function generate_auth_code($payload)
{
	$sharedSecret = get_application_key_setting();
	
	$signed_payload = $payload . "|" . $sharedSecret;
	
	$auth_code = sha1($signed_payload);
	$auth_code = strtoupper($auth_code);
	
	return $auth_code;
}

function validate_auth_code($payload, $auth_code)
{
	return (generate_auth_code($payload) == $auth_code);
}
?>